#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $CURRENT_DIR/../env.sh

repo_path=discover_repo_path
repo_path=$(get_tmux_option "@tfss_repo_path" "$default_repo_path")
session_launcher=$(get_tmux_option "@tfss_sesion_launcher" "$default_sesion_launcher")

if [[ $# -eq 1 ]] ; then
  session_dir=$1
else
  session_dir=$(fd '\.git$' "$repo_path" -H | sed -r 's@\.git?/$@@' | fzf)
fi

if [[ -z $session_dir ]]; then
  exit 0
fi

session=$(basename "$session_dir" | tr . _)
tmux_running=$(tmux ls|echo "$?")

if [ $tmux_running == "1" ] ; then
  #tmux new-session -s $session -c $session_dir
  tmux start-server
fi

if tmux has-session -t=$session 2> /dev/null; then
  tmux switch-client -t ${session}
  exit
else
  tmux new-session -ds $session -c $session_dir -n "localhost"
fi

$TFSS_SESSION_LAUNCHER "$session" "$session_dir"
